### ISSUE TITLE
Issue during Deserialization of ArrayList<Float>

### ISSUE THREAD

**Issue by vasgat** [helios-h2020/h.core-SocialEgoNetwork#1]
I have an object Profile that I want to store in the ego node of the contextual ego network. 

`egoNetwork.getEgo().getOrCreateInstance(Profile.class).setProfile(profile);`

where profile is an ArrayList of Floats

When I try then to deserialize the Profile after saving it the first time in the contextual ego network, I get the following exception: 

> java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Deserialization error for field class eu.h2020.helios_social.core.contextualegonetwork.Node.moduleData : java.lang.RuntimeException: java.lang.RuntimeException: Deserialization error for field class eu.h2020.helios_social.modules.contentawareprofiling.profile.CoarseInterestsProfile.rawProfile : java.lang.NoSuchMethodException: java.lang.Float.<init> []
> at eu.h2020.helios_social.core.contextualegonetwork.Utils.error(Utils.java:24)
> at eu.h2020.helios_social.core.contextualegonetwork.Utils.error(Utils.java:66)
> at eu.h2020.helios_social.core.contextualegonetwork.Serializer.reload(Serializer.java:487)
> at eu.h2020.helios_social.core.contextualegonetwork.Serializer.reload(Serializer.java:461)
> at eu.h2020.helios_social.core.contextualegonetwork.ContextualEgoNetwork.createOrLoad(ContextualEgoNetwork.java:89)

**Comment by maniospas** [comment]
Issue replicated in examples/ExampleSave
Found source of error: Floats were not treated as primitives (e.g. as Doubles were)
Fixed as of 1.0.2
