### ISSUE TITLE
Issue when trying to deserialize null values

### ISSUE THREAD

**Issue by vasgat** [helios-h2020/h.core-SocialEgoNetwork#2]
I try to save an object in the ego node that includes a null variable. If I save the ego network and try to deserialize it I get the following exception:
> java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Deserialization error for field class eu.h2020.helios_social.core.contextualegonetwork.Node.moduleData : java.lang.RuntimeException: java.lang.RuntimeException: Deserialization error for field class eu.h2020.helios_social.modules.contentawareprofiling.profile.CoarseInterestsProfile.imageContexts : java.lang.RuntimeException: Unclear deserialization null

**Comment by maniospas** [comment]
Issue replicated in examples/ExampleSave
Found source of error: json library migration deserialized nulls as json objects and needed an explicit string check instead
Fixed as of 1.0.3
